import Vue from "vue"
import Vuex from "vuex"

Vue.use(Vuex);

export default new Vuex.Store({
	state:{
		swiper:[  //首页轮播图数据
			{img:'../../static/0be7151a563fab4e13bf6c0f16bb64e.jpg'},
			{img:'../../static/2dc5b43eb9ca4e3980c37574edc9cc8.jpg'},
			{img:'../../static/4f99447b13d9bb267692919f82ebb80.jpg'},
			{img:'../../static/76888b61f6e0079fce214e6f79a7d94.jpg'}
		],
		homedata:[
			{
				id:0,
				deletect:false,
				cover:'../../static/ee08147e461f94519d36d4ac640243a.jpg',
				title:'新绿素物体表面消毒液衣物沙发卫生间消毒水家用室内地板杀菌除味360ML(3瓶顺丰包邮 蓝白)',
				price:129,
				parameter:{
					subject:[
						{
							brand:'霍尼韦尔(Honeywell)',
							Model:'-',
							type:'其他',
							measure:'10m²以下'
						}
					],
					Specifications:[
						{
						   Voltage:'-',
						   power:'-',
						   Netweight:'-'	  
						}
					],
					function:[
						{
							control:'机械版',
							operation:'其他方式',
							timing:'不支持',
							Purify:'除PM2.5'
						}
					]
				},
				coverurl:[
					'../../static/ee08147e461f94519d36d4ac640243a.jpg',
					'../../static/1.1.jpg',
					'../../static/1.2.jpg',
				],
				content:[
					'../../static/1.jpg',
					'../../static/2.jpg',
					'../../static/3.jpg',
					'../../static/4.jpg'
				]
			},
			{
				id:1,
				deletect:false,
				cover:'../../static/d636992edbf9c33261ddff60aa20fe8.jpg',
				title:'韩国杯具熊焖烧壶316不锈钢真空保温便当饭盒保温桶粥桶闷烧杯焖烧罐 带饭神器520ML',
				price:99,
				parameter:{
					subject:[
						{
							brand:'monbento',
							Model:'-',
							measure:'1件'
						}
					],
					Specifications:[
						{
						   Voltage:'-',
						   power:'不锈钢',
						   Netweight:'其他'	  
						}
					],
					function:[
						{
							control:'',
							operation:'',
							timing:'',
							Purify:''
						}
					]
				},
				coverurl:[
					'../../static/d636992edbf9c33261ddff60aa20fe8.jpg',
					'../../static/3%20(1).jpg',
					'../../static/3%20(2).jpg',
				],
				content:[
					'../../static/3.3.jpg',
					'../../static/3.4.jpg',
					'../../static/3.5.jpg',
					'../../static/3.6.jpg'
				]
			},
			{
				id:2,
				deletect:false,
				cover:'../../static/e001837779d2de96e5a3502a96cf010.jpg',
				title:'消毒液套装1瓶550ml空间消毒液+2瓶居家消毒液 顺丰即发(3瓶顺丰包邮 果绿)',
				price:129,
				parameter:{
					subject:[
						{
							brand:'霍尼韦尔(Honeywell)',
							Model:'-',
							type:'其他',
							measure:'10m²以下'
						}
					],
					Specifications:[
						{
						   Voltage:'-',
						   power:'-',
						   Netweight:'-'	  
						}
					],
					function:[
						{
							control:'机械版',
							operation:'其他方式',
							timing:'不支持',
							Purify:'除PM2.5+杀菌'
						}
					]
				},
				coverurl:[
					'../../static/e001837779d2de96e5a3502a96cf010.jpg',
					'../../static/4.1.jpg',
					'../../static/4.2.jpg',
				],
				content:[
					'../../static/4.3.jpg',
					'../../static/4.4.jpg',
					'../../static/4.5.jpg',
					'../../static/4.6.jpg'
				]
			},
			{
				id:3,
				deletect:false,
				cover:'../../static/c49b4e117c63815ae8766283e9baea0.jpg',
				title:'展望可爱多 75度酒精湿纸巾10抽*10包(疫情期间工厂人力有限 按照下单顺序30天内发货完成)',
				price:29.90,
				parameter:{
					subject:[
						{
							brand:'展望可爱多(ZW.KOIDO)',
							Model:'组合装',
							measure:'24个月'
						}
					],
					Specifications:[
						{
						   Voltage:'国产',
						   power:'棉柔',
						   Netweight:'均码'	  
						}
					],
					function:[
						{
							control:'通用',
							operation:'',
							timing:'',
							Purify:''
						}
					]
				},
				coverurl:[
					'../../static/c49b4e117c63815ae8766283e9baea0.jpg',
					'../../static/5.1.jpg',
					'../../static/5.2.jpg',
				],
				content:[
					'../../static/5.3.jpg',
					'../../static/5%20(1).jpg',
					'../../static/5%20(2).jpg',
					'../../static/5%20(3).jpg'
				]
			},
			{
				id:4,
				deletect:false,
				cover:'../../static/17ce2764b48ca7dd0e18efd05e1023b.jpg',
				title:'爱莫生 (airmotion) Woobi Girl清吸口罩 胭脂红 防雾霾PM2.5 防花粉粉尘颗粒 防二手烟细菌异味',
				price:199,
				parameter:{
					subject:[
						{
							brand:'-',
							Model:'-',
							measure:'-'
						}
					],
					Specifications:[
						{
						   Voltage:'-',
						   power:'-',
						   Netweight:'-'	  
						}
					],
					function:[
						{
							control:'-',
							operation:'-',
							timing:'-',
							Purify:'-'
						}
					]
				},
				coverurl:[
					'../../static/17ce2764b48ca7dd0e18efd05e1023b.jpg',
					'../../static/6%20(1).jpg',
					'../../static/6%20(2).jpg',
				],
				content:[
					'../../static/6.3.jpg',
					'../../static/6.4.jpg',
					'../../static/6.5.jpg',
					'../../static/6.6.jpg'
				]
			},
			{
				id:5,
				deletect:false,
				cover:'../../static/f40885e1bbcbca37bcfe63eb8065b78.jpg',
				title:'爱莫生(airmotion) Pro Edge多功能清吸口罩 心悦纯白 防雾霾PM2.5 防花粉粉尘颗粒放二手烟',
				price:199,
				parameter:{
					subject:[
						{
							brand:'-',
							Model:'-',
							measure:'-'
						}
					],
					Specifications:[
						{
						   Voltage:'-',
						   power:'-',
						   Netweight:'-'	  
						}
					],
					function:[
						{
							control:'-',
							operation:'-',
							timing:'-',
							Purify:'-'
						}
					]
				},
				coverurl:[
					'../../static/f40885e1bbcbca37bcfe63eb8065b78.jpg',
					'../../static/7%20(1).jpg',
					'../../static/7%20(2).jpg',
				],
				content:[
					'../../static/17a78d4b3268ecb2d5dfb52da3651bd.jpg',
					'../../static/a1def0b0230f77aa020b4bfad6985c3.jpg',
					'../../static/d6d3b02a970b226da4da15a0d9ee410.jpg',
					'../../static/c1431919b1066bafd6bebc8541932fb.jpg'
				]
			},
			{
				id:6,
				deletect:false,
				cover:'../../static/a5bd3d95ea535dddf2e0acff121dade.jpg',
				title:'蓝月亮 衣物消毒液套装 1kg*3瓶(默认 默认)',
				price:71.70,
				parameter:{
					subject:[
						{
							brand:'蓝月亮',
							Model:'国产',
							measure:'3kg'
						}
					],
					Specifications:[
						{
						   Voltage:'消毒剂',
						   power:'无味',
						   Netweight:'24个月'	  
						}
					],
					function:[
						{
							control:'箱装',
							operation:'2L及以上',
							timing:'消毒/抗菌',
							Purify:'-'
						}
					]
				},
				coverurl:[
					'../../static/a5bd3d95ea535dddf2e0acff121dade.jpg',
					'../../static/7.5.jpg',
					'../../static/7.6.jpg',
				],
				content:[
					'../../static/7.5.jpg',
					'../../static/7.6.jpg',
					'../../static/7.7.jpg',
					'../../static/7.8.jpg'
				]
			},
			{
				id:7,
				deletect:false,
				cover:'../../static/24c97d7f70452d7587682de1a92640c.jpg',
				title:'Dettol滴露 消毒液750ml 家居清洁消毒 衣被消毒 除菌除螨 皮肤消毒杀菌率99.999%(750ml)',
				price:53.90,
				parameter:{
					subject:[
						{
							brand:'滴露',
							Model:'国产',
							measure:'消毒液750ml'
						}
					],
					Specifications:[
						{
						   Voltage:'消毒剂',
						   power:'其他',
						   Netweight:'36个月'	  
						}
					],
					function:[
						{
							control:'瓶装',
							operation:'2L及以上',
							timing:'消毒/抗菌',
							Purify:'-'
						}
					]
				},
				coverurl:[
					'../../static/24c97d7f70452d7587682de1a92640c.jpg',
					'../../static/9%20(1).jpg',
					'../../static/9%20(2).jpg',
				],
				content:[
					'../../static/9%20(1).jpg',
					'../../static/9%20(2).jpg',
					'../../static/9%20(3).jpg',
					'../../static/9%20(4).jpg'
				]
			},
			{
				id:8,
				deletect:false,
				cover:'../../static/0764a6e94220b68b153895326f7517c.jpg',
				title:'Dettol滴露 健康抑菌洗手液500g送300g滋润双手 抑菌99.9% 适合全家长期使用 新疆西藏不发货',
				price:15.90,
				parameter:{
					subject:[
						{
							brand:'滴露',
							Model:'国产',
							measure:'洗手液'
						}
					],
					Specifications:[
						{
						   Voltage:'-',
						   power:'卫浴清洁',
						   Netweight:'36个月'	  
						}
					],
					function:[
						{
							control:'-',
							operation:'-',
							timing:'-',
							Purify:'-'
						}
					]
				},
				coverurl:[
					'../../static/0764a6e94220b68b153895326f7517c.jpg',
					'../../static/10%20(1).jpg',
					'../../static/10%20(2).jpg',
				],
				content:[
					'../../static/10%20(1).jpg',
					'../../static/10%20(2).jpg',
					'../../static/10%20(3).jpg',
					'../../static/10%20(4).jpg'
				]
			},
			{
				id:9,
				deletect:false,
				cover:'../../static/56101516d5d007e4ff3cc35e55bccfc.jpg',
				title:'Dettol滴露 泡沫抑菌洗手液樱桃芬芳250ml+225+225ml 5秒抑菌 高效抑菌 新疆西藏不发货',
				price:36.90,
				parameter:{
					subject:[
						{
							brand:'滴露',
							Model:'国产',
							measure:'洗手液'
						}
					],
					Specifications:[
						{
						   Voltage:'樱桃芬芳250ml＋225＋225ml',
						   power:'卫浴清洁',
						   Netweight:'36个月'	  
						}
					],
					function:[
						{
							control:'-',
							operation:'-',
							timing:'-',
							Purify:'-'
						}
					]
				},
				coverurl:[
					'../../static/56101516d5d007e4ff3cc35e55bccfc.jpg',
					'../../static/11%20(1).jpg',
					'../../static/11%20(2).jpg',
				],
				content:[
					'../../static/11%20(1).jpg',
					'../../static/11%20(2).jpg',
					'../../static/11%20(3).jpg',
					'../../static/11%20(4).jpg'
				]
			},	
		]
	}
})